service:
  greet:
    message: it's my new message

property:
  name: some_table_name
  
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        Physical-strategy: ru.rgx.evo.config.MySpringPhysicalNamingStrategy
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true